name: 'PlantUML Generator'
description: 'Run PlantUML tool with the given set of arguments to generate various diagrams'
author: '@oinume'

inputs:
  args:
    description: 'Arguments for PlantUML tool'
    required: true
    default: '-h'

runs:
  using: 'docker'
  image: 'docker://oinume/plantuml-github-action:push-docker-image'
  args:
    - ${{ inputs.args }}

branding:
  icon: 'underline'
  color: 'blue'
